### ISSUE TITLE
add more explicit dependencies for karma-sinon-chai to fix lolex dep issue on tests

### ISSUE THREAD

**Issue by legendtang** [aframevr/aframe#1097]
When I run `npm test`, here is the output: 

````
> aframe@0.2.0 test E:\github\aframe
> karma start ./tests/karma.conf.js

06 03 2016 01:57:17.760:INFO [preprocessor.env]: Publishing variables:  [ 'TEST_ENV' ]
module.js:341
    throw err;
    ^

Error: Cannot find module 'lolex'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.require.resolve (internal/module.js:23:19)
    at framework (E:\github\aframe\node_modules\karma-sinon-chai\index.js:26:40)
    at Array.invoke (E:\github\aframe\node_modules\di\lib\injector.js:75:15)
    at get (E:\github\aframe\node_modules\di\lib\injector.js:48:43)
    at E:\github\aframe\node_modules\karma\lib\server.js:138:20
    at Array.forEach (native)
    at Server._start (E:\github\aframe\node_modules\karma\lib\server.js:137:21)
    at invoke (E:\github\aframe\node_modules\di\lib\injector.js:75:15)
    at Server.start (E:\github\aframe\node_modules\karma\lib\server.js:102:18)
    at Object.exports.run (E:\github\aframe\node_modules\karma\lib\cli.js:243:26)
    at Object.<anonymous> (E:\github\aframe\node_modules\karma\bin\karma:3:23)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
npm ERR! Test failed.  See above for more details.
````

I noticed it was reported in https://github.com/kmees/karma-sinon-chai/issues/26 and the latest version has fixed the issue. So it is time to bump this dependency version?

**Comment by nylki** [comment]
In the meantime, doing a manual `npm install lolex chai sinon sinon-chai` worked for me to start `karma`/`npm test`.

**Comment by ngokevin** [comment]
@legendtang want to bump karma-sinon-chai?

**Comment by legendtang** [comment]
@ngokevin From what I've seen, the v1.2.0 of karma-sinon-chai doesn't fix that issue since they use `peerDependencies` instead of `dependencies`. As @nylki said, we need to add them as more explicit dependencies.
