### ISSUE TITLE
inconsistent a-scene clock test

### ISSUE THREAD

**Issue by machenmusik** [aframevr/aframe#2608]
sometimes when running `npm run test:chrome`
this happens:
```
SUMMARY:
√ 825 tests completed
i 2 tests skipped
× 1 test failed

FAILED TESTS:
  a-scene (with renderer)
    × clock
      Chrome 57.0.2987 (Windows 10 0.0.0)
    AssertionError: expected 0 to be above 0
        at Function.assert.isAbove (node_modules/chai/chai.js:2405:35)
        at Context.<anonymous> (c:/Users/machenmusik/AppData/Local/Temp/tests/core/scene/a-scene.test.js:416:0 <- C:/Users/machenmusik/AppData/Local/Temp/472879a1449f76b792fa2ebcec1be11b.browserify:88162:12)
```

**Comment by ngokevin** [comment]
Dupe https://github.com/aframevr/aframe/issues/2546
