### ISSUE TITLE
Figure out why npm is giving me a hassle with "npm ERR! registry error parsing json"

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe#291]
When I run `npm publish` from the `aframe` repo, the push succeeds (after a minute or so), but the command actually hangs and shows this error … forever (until I `Control + C` it):

```
% npm publish                                              /opt/aframe (master)
npm ERR! registry error parsing json
npm ERR! registry error parsing json
```

```
% git push --tags                                          /opt/aframe (master)
Total 0 (delta 0), reused 0 (delta 0)
To git@github.com:aframevr/aframe.git
 * [new tag]         v0.1.0 -> v0.1.0
% npm publish                                              /opt/aframe (master)
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! publish Failed PUT 502
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "publish"
npm ERR! node v0.12.7
npm ERR! npm  v2.12.1

npm ERR! Unexpected token <
npm ERR! <html><body><h1>502 Bad Gateway</h1>
npm ERR! The server returned an invalid or incomplete response.
npm ERR! </body></html>
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/aframe/npm-debug.log
% cat npm-debug.log                                        /opt/aframe (master)
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'publish' ]
2 info using npm@2.12.1
3 info using node@v0.12.7
4 verbose node symlink /usr/local/bin/node
5 verbose publish [ '.' ]
6 silly cache add args [ '.', null ]
7 verbose cache add spec .
8 silly cache add parsed spec { raw: '.',
8 silly cache add   scope: null,
8 silly cache add   name: null,
8 silly cache add   rawSpec: '.',
8 silly cache add   spec: '/opt/aframe',
8 silly cache add   type: 'directory' }
9 verbose addLocalDirectory /Users/cvan/.npm/aframe/0.1.0/package.tgz not in flight; packing
10 verbose tar pack [ '/Users/cvan/.npm/aframe/0.1.0/package.tgz', '/opt/aframe' ]
11 verbose tarball /Users/cvan/.npm/aframe/0.1.0/package.tgz
12 verbose folder /opt/aframe
13 info prepublish aframe@0.1.0
14 verbose addLocalTarball adding from inside cache /Users/cvan/.npm/aframe/0.1.0/package.tgz
15 silly cache afterAdd aframe@0.1.0
16 verbose afterAdd /Users/cvan/.npm/aframe/0.1.0/package/package.json not in flight; writing
17 verbose afterAdd /Users/cvan/.npm/aframe/0.1.0/package/package.json written
18 silly publish { name: 'aframe',
18 silly publish   version: '0.1.0',
18 silly publish   description: 'Building blocks for the VR Web',
18 silly publish   main: 'index.js',
18 silly publish   scripts:
18 silly publish    { start: 'npm run dev',
18 silly publish      dev: 'npm run build && node ./scripts/budo',
18 silly publish      browserify: 'browserify ./index.js -s \'AFRAME\'',
18 silly publish      build: 'mkdir -p build/ && npm run browserify -- --debug -o build/aframe.js',
18 silly publish      dist: 'mkdir -p dist/ && npm run browserify -s -- --debug | exorcist dist/aframe.js.map > dist/aframe.js && uglifyjs dist/aframe.js -c warnings=false -m -o dist/aframe.min.js',
18 silly publish      preghpages: 'npm run dist && rm -rf gh-pages && mkdir -p gh-pages && cp -r {.nojekyll,dist,lib,examples,index.html,style} gh-pages/. 2>/dev/null || : && git checkout dist/ && replace \'build/aframe.js\' \'dist/aframe.min.js\' gh-pages/ -r --silent',
18 silly publish      ghpages: 'node ./scripts/gh-pages',
18 silly publish      'gh-pages': 'npm run ghpages',
18 silly publish      'release:bump': 'npm version patch --preminor',
18 silly publish      'release:push': 'npm login && npm publish && git push --follow-tags',
18 silly publish      lint: 'semistandard -v $(git ls-files \'*.js\') | snazzy',
18 silly publish      precommit: 'npm run lint' },
18 silly publish   repository:
18 silly publish    { type: 'git',
18 silly publish      url: 'git+https://github.com/aframevr/aframe.git' },
18 silly publish   license: 'MIT',
18 silly publish   devDependencies:
18 silly publish    { browserify: '^11.0.1',
18 silly publish      'browserify-css': '^0.8.2',
18 silly publish      budo: '^7.0.2',
18 silly publish      exorcist: '^0.4.0',
18 silly publish      'gh-pages': '^0.4.0',
18 silly publish      'html-minifier': '^0.8.0',
18 silly publish      husky: '^0.10.1',
18 silly publish      polymerize: '^1.0.0',
18 silly publish      replace: '^0.3.0',
18 silly publish      semistandard: '^7.0.2',
18 silly publish      snazzy: '^2.0.1',
18 silly publish      uglifyjs: '^2.4.10' },
18 silly publish   dependencies: { 'aframe-core': '^0.1.1' },
18 silly publish   link: true,
18 silly publish   browserify: { transform: [ [Object] ] },
18 silly publish   semistandard: { ignore: [ 'build/**', 'dist/**', 'lib/vendor/**', 'examples/_js/**' ] },
18 silly publish   keywords:
18 silly publish    [ 'aframe',
18 silly publish      'aframe-core',
18 silly publish      'vr',
18 silly publish      'webvr',
18 silly publish      '3d',
18 silly publish      'three',
18 silly publish      'components',
18 silly publish      'elements' ],
18 silly publish   readme: '# aframe\n\n__Building blocks for the VR Web.__\n\nTo learn more, head over to the [A-Frame site](https://aframe.io/) for [examples](https://aframe.io/examples/), [docs](https://aframe.io/docs/), and [FAQ](https://aframe.io/faq/).\n\n> For the core library, check out [A-Frame Core](https://github.com/aframevr/aframe-core/).\n\n\n## Usage\n\n### CodePen\n\nIf you want to get started immediately, just fire up [__this CodePen example scene__](http://codepen.io/team/mozvr/pen/BjygdO?editors=100)!\n\n### Downloads\n\nIf you would like to embed this library in your project, simply include this file:\n\n* [`aframe.min.js`](https://aframe.io/releases/latest/aframe.min.js)\n\nOr if you\'d prefer the unminified version for local development (with source maps):\n\n* [`aframe.js`](https://aframe.io/releases/latest/aframe.js)\n\n__Also, be sure to check out the awesome [examples](https://aframe.io/examples/) (or [the ones in this repository](examples/)).__\n\n### npm\n\nFirst install from npm:\n\n    npm install aframe\n\nAnd in your Browserify/Webpack modules, simply require the module:\n\n    require(\'aframe\')\n\n\n## Local installation and development\n\nAlternatively, you can clone this repository to work locally on this project and explore the examples.\n\n    git clone git@github.com:aframevr/aframe.git\n    cd aframe && npm install\n\nTo start the local development server:\n\n    npm start\n\nAnd fire up __[http://localhost:9000](http://localhost:9000)__!\n\n## Browser console logging\n\nIf you\'d like to see helpful logs, warnings, and errors, you can enable logging from the console of your favourite developer tools:\n\n    localStorage.logs = 1\n\nAnd to disable:\n\n    localStorage.logs = 0\n\n\n## Maintainers\n\nEnsure you have [cloned the repo and installed the dependencies](#local-installation-and-development).\n\n### Developing alongside the other aframe packages (e.g., [`aframe-core`](https://github.com/aframevr/aframe-core/))\n\nIf you want to make changes to the [__`aframe-core`__](https://github.com/aframevr/aframe-core/) library and test with `aframe`, you\'ll need to run these commands to link things up correctly.\n\n#### Linking\n\nWhen you are in the directory of your __`aframe-core`__ repo checkout:\n\n    npm link\n\nWhen you are in the directory of your __`aframe`__ repo checkout:\n\n    npm link aframe-core\n\nNow when you make changes to `aframe-core`, those changes will get reflected when a bundle gets built (the page is refreshed or a `aframe` file is changed), so you can test the `aframe-core` dependency against `aframe` without having to manually push things to `npm` for testing (which is a big no no!).\n\n#### Unlinking\n\nYou\'ll need to `npm unlink` when you are done testing things and want to actually use the npm-published versions, not your versions that are locally linked.\n\nFrom your __`aframe-core`__ directory:\n\n    npm unlink\n\nFrom your __`aframe`__ directory:\n\n    npm unlink aframe-core\n\n\n### Releasing and publishing a new version to [npm](https://www.npmjs.com/)\n\nTo increment the preminor version of the package (e.g., `0.1.19` to `0.1.20`) and create a git tag (e.g., `v0.1.20`):\n\n    npm run release:bump\n\n___NOTE:___ npm versions __cannot__ be unpublished.\n\nOnce the package is 100% ready to go, to push the new version to npm (e.g., `0.1.20`) and to the new tag to GitHub (e.g., `v0.1.20`):\n\n    npm run release:push\n\n## Updating `dist` files\n\n    npm run dist\n    git commit -am \'Bump dist\'\n\n## Publishing to GitHub Pages\n\nTo publish to __https://aframevr.github.io/aframecore/__:\n\n    npm run ghpages\n\nTo publish to __https://your_username.github.io/aframe/__:\n\n    npm run ghpages your_username\n\n## License\n\nThis program is free software and is distributed under an [MIT License](LICENSE).\n',
18 silly publish   readmeFilename: 'README.md',
18 silly publish   gitHead: '44ebf01c667f17dfd78f816c4668f0d5f014e90b',
18 silly publish   bugs: { url: 'https://github.com/aframevr/aframe/issues' },
18 silly publish   homepage: 'https://github.com/aframevr/aframe#readme',
18 silly publish   _id: 'aframe@0.1.0',
18 silly publish   _shasum: '6ff52db4d9e8e3a7806d20b131e7d47cb368a0dc',
18 silly publish   _from: '.' }
19 verbose getPublishConfig undefined
20 silly mapToRegistry name aframe
21 silly mapToRegistry scope (from config) @mozvr
22 silly mapToRegistry registry https://registry.npmjs.org/
23 silly mapToRegistry uri https://registry.npmjs.org/aframe
24 verbose publish registryBase https://registry.npmjs.org/
25 silly publish uploading /Users/cvan/.npm/aframe/0.1.0/package.tgz
26 verbose request uri https://registry.npmjs.org/aframe
27 verbose request sending authorization for write operation
28 info attempt registry request try #1 at 01:23:09
29 verbose request using bearer token for auth
30 verbose request id e91a19ffdf33e1ca
31 http request PUT https://registry.npmjs.org/aframe
32 http 504 https://registry.npmjs.org/aframe
33 verbose bad json <html><body><h1>504 Gateway Time-out</h1>
33 verbose bad json The server didn't respond in time.
33 verbose bad json </body></html>
34 error registry error parsing json
35 info retry will retry, error on last attempt: SyntaxError: Unexpected token <
35 info retry <html><body><h1>504 Gateway Time-out</h1>
35 info retry The server didn't respond in time.
35 info retry </body></html>
36 info attempt registry request try #2 at 01:26:50
37 verbose request using bearer token for auth
38 http request PUT https://registry.npmjs.org/aframe
39 http 504 https://registry.npmjs.org/aframe
40 verbose bad json <html><body><h1>504 Gateway Time-out</h1>
40 verbose bad json The server didn't respond in time.
40 verbose bad json </body></html>
41 error registry error parsing json
42 info retry will retry, error on last attempt: SyntaxError: Unexpected token <
42 info retry <html><body><h1>504 Gateway Time-out</h1>
42 info retry The server didn't respond in time.
42 info retry </body></html>
43 info attempt registry request try #3 at 01:31:18
44 verbose request using bearer token for auth
45 http request PUT https://registry.npmjs.org/aframe
46 http 502 https://registry.npmjs.org/aframe
47 verbose bad json <html><body><h1>502 Bad Gateway</h1>
47 verbose bad json The server returned an invalid or incomplete response.
47 verbose bad json </body></html>
48 error registry error parsing json
49 verbose headers { 'content-type': 'text/html',
49 verbose headers   'cache-control': 'max-age=300',
49 verbose headers   'transfer-encoding': 'chunked',
49 verbose headers   'accept-ranges': 'bytes',
49 verbose headers   date: 'Thu, 17 Dec 2015 09:34:27 GMT',
49 verbose headers   via: '1.1 varnish',
49 verbose headers   connection: 'keep-alive',
49 verbose headers   'x-served-by': 'cache-lax1421-LAX',
49 verbose headers   'x-cache': 'MISS',
49 verbose headers   'x-cache-hits': '0',
49 verbose headers   'x-timer': 'S1450344679.558400,VS0,VE187888' }
50 verbose request invalidating /Users/cvan/.npm/registry.npmjs.org/aframe on PUT
51 error publish Failed PUT 502
52 verbose stack SyntaxError: Unexpected token <
52 verbose stack <html><body><h1>502 Bad Gateway</h1>
52 verbose stack The server returned an invalid or incomplete response.
52 verbose stack </body></html>
52 verbose stack
52 verbose stack
52 verbose stack     at Object.parse (native)
52 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:197:23)
52 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:170:14)
52 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:197:22)
52 verbose stack     at Request.emit (events.js:110:17)
52 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1050:14)
52 verbose stack     at Request.emit (events.js:129:20)
52 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:996:12)
52 verbose stack     at IncomingMessage.emit (events.js:129:20)
52 verbose stack     at _stream_readable.js:908:16
53 verbose cwd /opt/aframe
54 error Darwin 14.5.0
55 error argv "node" "/usr/local/bin/npm" "publish"
56 error node v0.12.7
57 error npm  v2.12.1
58 error Unexpected token <
58 error <html><body><h1>502 Bad Gateway</h1>
58 error The server returned an invalid or incomplete response.
58 error </body></html>
59 error If you need help, you may report this error at:
59 error     <https://github.com/npm/npm/issues>
60 verbose exit [ 1, true ]

% npm run release:bump                                                                                                         /opt/aframe (master)

> aframe@0.1.0 release:bump /opt/aframe
> npm version patch --preminor

v0.1.1

% npm run release:push                                                                                                         /opt/aframe (master)

> aframe@0.1.1 release:push /opt/aframe
> npm login && npm publish && git push --follow-tags

Username: mozvr
Password: 
Email: (this IS public) cvan@mozilla.com
npm ERR! registry error parsing json
npm ERR! registry error parsing json
```

**Comment by ngokevin** [comment]
should be resolved by now
