### ISSUE TITLE
"360° Image Gallery" tutorial out of date?

### ISSUE THREAD

**Issue by anselanza** [aframevr/aframe#3368]
**Description:**

- A-Frame Version: 0.7.1
- Platform / Device: Firefox 58 on MacOS
- Reproducible Code Snippet or URL:

I have been following the Guides in the Docs, and it seems that one of the Community components recommended in the tutorial <del>no longer even exists</del> has been moved. Specifically, under *Using Community Components* section, there is an instruction to `angle install template`, but this always fails:
```
Installing A-Frame component `template` to `index.html`
A-Frame script tag not found. Assuming latest version.
/usr/local/lib/node_modules/angle/lib/install.js:68
  if (!file) { throw new Error(`${moduleName} not found in A-Frame registry`); }
               ^

Error: template not found in A-Frame registry
    at Command.install (/usr/local/lib/node_modules/angle/lib/install.js:68:22)
    at Command.listener (/usr/local/lib/node_modules/angle/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (/usr/local/lib/node_modules/angle/node_modules/commander/index.js:653:12)
    at Command.parse (/usr/local/lib/node_modules/angle/node_modules/commander/index.js:475:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/angle/index.js:33:4)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
```

A working link to https://ngokevin.github.io/kframe/components/template/ is provided at one point in the document, but the link provided further down in the docs https://github.com/ngokevin/aframe-template-component is 404 not found. Clearly the latter is what is being used in the A-frame registry.

I guess the Template component could be installed manually from the correct location, but this is a beginner guide, so either the instructions need to be fixed (don't use `angle`?) or the registry needs to be updated?

**Comment by ngokevin** [comment]
I've removed the angle pieces. thanks!

**Comment by anselanza** [comment]
Great, thank you!
