### ISSUE TITLE
"Failed to execute 'end' on 'XRSession' error exiting VR

### ISSUE THREAD

**Issue by klausw** [aframevr/aframe#4321]
**Description:**

- A-Frame Version: 49b3f03452876831c55b9b761dbdf81d2a28a7bb (master, Oct 21 2019)
- Platform / Device: Android with Daydream View
- Reproducible Code Snippet or URL: https://klausw.github.io/a-frame-car-sample/index.html

How to reproduce:

- open https://klausw.github.io/a-frame-car-sample/index.html
- press "Enter VR" button
- exit VR session

JS console shows errors:

```
session end CustomEvent {isTrusted: false, detail: {…}, type: "exit-vr", target: a-scene, currentTarget: a-scene, …}
aframe-master.js:77067 Uncaught (in promise) DOMException: Failed to execute 'end' on 'XRSession': XRSession has already ended.
    at HTMLElement.exitVR (https://klausw.github.io/a-frame-car-sample/dist/aframe-master.js:77067:28)
    at XRSession.exitVRBound (https://klausw.github.io/a-frame-car-sample/dist/aframe-master.js:76786:47)
exitVR @ aframe-master.js:77067
exitVRBound @ aframe-master.js:76786
aframe-master.js:81177 Uncaught TypeError: Cannot read property 'length' of null
    at NewSystem.updateControllerList (aframe-master.js:81177)
    at bound (aframe-master.js:81198)
    at NewSystem.throttledUpdateControllerList (aframe-master.js:81748)
    at NewSystem.tick (aframe-master.js:81169)
    at HTMLElement.tick (aframe-master.js:77393)
    at HTMLElement.render (aframe-master.js:77437)
    at bound (aframe-master.js:81198)
    at onAnimationFrame (aframe-master.js:30949)
    at onAnimationFrame (aframe-master.js:21409)
```

After this, the render loop is no longer working, presumably due to `tick` getting an exception.

**Comment by klausw** [comment]
Also reproduces on https://mini-mastodon.glitch.me/ which uses https://cdn.jsdelivr.net/gh/aframevr/aframe@df3e8672b77568845e5e360f54f4456fd4829a38/dist/aframe-master.min.js

**Comment by Leshao-Zhang** [comment]
I did not get this error anymore with https://mini-mastodon.glitch.me/ . Guess it was fixed.

However, I still had screen.orintation.lock() problem with https://klausw.github.io/a-frame-car-sample/index.html

#4301
