### ISSUE TITLE
yarn/npm complaining about envify and browserify css

### ISSUE THREAD

**Issue by QuinnCiccoretti** [aframevr/aframe#4645]
**Description:**
Somethings up with browserify, errors out on fresh aframe install. Similar to #2187 and #1823.
- A-Frame Version: 1.0.4
- Reproducible Code Snippet or URL:
### Yarn 
```bash
mkdir test && cd test
yarn add aframe
yarn add -D browserify
echo 'require("aframe")' > index.js
yarn run browserify index.js -o bundle.js
```
### NPM
```bash
mkdir test && cd test
npm install aframe
echo 'require("aframe")' > index.js
browserify index.js -o bundle.js  # add a simple build script if you have no global browserify
```

On both package managers I get:
```
Error: Cannot find module 'browserify-css' from '/home/qciccoretti/test/node_modules/aframe'
    at /home/qciccoretti/test/node_modules/resolve/lib/async.js:115:35
    at processDirs (/home/qciccoretti/test/node_modules/resolve/lib/async.js:268:39)
    at isdir (/home/qciccoretti/test/node_modules/resolve/lib/async.js:275:32)
    at /home/qciccoretti/test/node_modules/resolve/lib/async.js:25:69
    at FSReqCallback.oncomplete (fs.js:167:21)
```
Or 
```
Error: Cannot find module 'envify' from '/home/qciccoretti/test/node_modules/aframe'
```
with the same stack trace. These packages are listed as browserify transforms. Installing them as dependencies fixes the issue, but it seems kind of wack. What should I do?

**Comment by vincentfretin** [comment]
We don't use browserify anymore, you can close @dmarcos
