### ISSUE TITLE
node v18 crashes with audio src

### ISSUE THREAD

**Issue by neverlose-lv** [aframevr/aframe#5055]
**Description:**
Just updated to the latest Angular/Node version.
Now the node crashes, when providing <audio src="..."> inside <a-assets>.

```
node:events:505
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot set property closed of #<Readable> which has only a getter
    at FsReadStream.close (/Users/apower/Desktop/VR_Tours/node_modules/memfs/lib/volume.js:2047:17)
    at FsReadStream._destroy (/Users/apower/Desktop/VR_Tours/node_modules/memfs/lib/volume.js:2032:10)
    at _destroy (node:internal/streams/destroy:109:10)
    at class_1.destroy (node:internal/streams/destroy:71:5)
    at class_1.<anonymous> (/Users/apower/Desktop/VR_Tours/node_modules/memfs/lib/volume.js:1962:22)
    at class_1.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1344:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on class_1 instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

Node.js v18.0.0

- A-Frame Version: 1.3
- Platform / Device: Mac OS
- Reproducible Code Snippet or URL: 

```
<a-scene>
  <a-assets>
    <audio src="assets/sounds/click.ogg"></audio>
  </a-assets>
</a-scene>
```

Package.json:

```
{
  "name": "vr-tours",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~13.3.6",
    "@angular/common": "~13.3.6",
    "@angular/compiler": "~13.3.6",
    "@angular/core": "~13.3.6",
    "@angular/forms": "~13.3.6",
    "@angular/platform-browser": "~13.3.6",
    "@angular/platform-browser-dynamic": "~13.3.6",
    "@angular/router": "~13.3.6",
    "aframe": "^1.3.0",
    "aframe-event-set-component": "^5.0.0",
    "aframe-layout-component": "^5.3.0",
    "aframe-proxy-event-component": "^2.1.0",
    "angular-aframe-pipe": "^1.0.0",
    "default-passive-events": "^2.0.0",
    "rxjs": "~7.5.5",
    "tslib": "^2.4.0",
    "zone.js": "~0.11.5"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~13.3.5",
    "@angular/cli": "~13.3.5",
    "@angular/compiler-cli": "~13.3.6",
    "@types/jasmine": "~4.0.3",
    "@types/node": "^17.0.31",
    "jasmine-core": "~4.1.1",
    "karma": "~6.3.19",
    "karma-chrome-launcher": "~3.1.1",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "typescript": "~4.6.4"
  }
}
```

**Comment by neverlose-lv** [comment]
Alright, this is not the aframe issue. Since node crashes even for default HTML `audio` tag, without loading aframe

**Comment by dmarcos** [comment]
Ok. thanks. Best of luck. Closing.

**Comment by stevenraysimon** [comment]
I'm having this issue as well with node v18.1
I'm building a Vue 3 app and HTML audio tag crashes the app.

TypeError: Cannot set property closed of #<Readable> which has only a getter

If I remove the audio tag it works. Any solutions to this?

**Comment by tindl88** [comment]
Just add some lines to `package.json`. 

```
{
  ...
  "resolutions": {
    "memfs": "3.4.7"
  }
}
```

**Comment by iampranavdhar** [comment]
This issue still persists

**Comment by dafnecaneda** [comment]
Hello ! I was able to resolve this issue by doing npm i memfs
I hope this can resolve others peoples issues too, good luck !
