### ISSUE TITLE
Errors and warnings in the examples

### ISSUE THREAD

**Issue by vincentfretin** [aframevr/aframe#5184]
**Description:**

I just tested all examples and noted the errors and warnings in this issue.
If anyone want to create a PR to fix one of those, please go ahead.

- A-Frame Version: master Dec 7, 2022 threejs r147
- Platform / Device: desktop
- Reproducible Code Snippet or URL: npm run start:https

- [ ] https://192.168.1.15:8080/showcase/hand-tracking/
```
three.module.js:8817 THREE.MeshStandardMaterial: 'skinning' is not a property of this material.
```

- [ ] https://192.168.1.15:8080/showcase/link-traversal/
```
aframe-tooltip-component.js:94 Uncaught (in promise) TypeError: geometry.addAttribute is not a function
    at NewComponent.init (aframe-tooltip-component.js:94:16)
    at NewComponent.initComponent (component.js:323:10)
    at NewComponent.updateProperties (component.js:305:12)
    at AEntity.updateComponent (a-entity.js:466:17)
    at AEntity.updateComponents (a-entity.js:442:12)
    at entityLoadCallback (a-entity.js:243:12)
    at emitLoaded (a-node.js:143:17)
```

on clicking on Egypt
```
aframe-environment-component.min.js:2 Uncaught (in promise) TypeError: r[0].applyMatrix is not a function
    at NewComponent.updateDressing (aframe-environment-c…onent.min.js:2:5329)
    at NewComponent.update (aframe-environment-c…nent.min.js:1:28723)
    at NewComponent.initComponent (component.js:333:10)
    at NewComponent.updateProperties (component.js:305:12)
    at module.exports.Component (component.js:81:8)
    at new NewComponent (component.js:665:15)
    at AScene.initComponent (a-entity.js:319:17)
    at AScene.updateComponent (a-entity.js:471:10)
    at AScene.updateComponent (a-scene.js:682:39)
    at AScene.updateComponents (a-entity.js:442:12)
```
This one is fixed in https://github.com/supermedium/aframe-environment-component/pull/78

- [ ] https://192.168.1.15:8080/showcase/model-viewer/
```
aframe-extras.min.js:7 Uncaught TypeError: Cannot read properties of undefined (reading 'radToDeg')
    at 80 (aframe-extras.min.js:7:21519)
    at n (aframe-extras.min.js:1:254)
    at aframe-extras.min.js:1:305
    at 81../checkpoint-controls (aframe-extras.min.js:7:22998)
    at n (aframe-extras.min.js:1:254)
    at aframe-extras.min.js:1:305
    at 2../src/controls (aframe-extras.min.js:1:531)
    at n (aframe-extras.min.js:1:254)
    at aframe-extras.min.js:1:305
    at 1../ (aframe-extras.min.js:1:459)
```
This is fixed in latest aframe-extras master build, latest is https://cdn.jsdelivr.net/gh/n5ro/aframe-extras@09b8445/dist/aframe-extras.min.js

```
raycaster:warn [raycaster] For performance, please define raycaster.objects when using raycaster or cursor components to whitelist which entities to intersect with. e.g., raycaster="objects: [data-raycastable]". 
browser.js:111 components:raycaster:warn [raycaster] For performance, please define raycaster.objects when using raycaster or cursor components to whitelist which entities to intersect with. e.g., raycaster="objects: [data-raycastable]". 
2
browser.js:111 core:schema:warn Unknown property `model` for component/system `generic-tracked-controller-controls`. 
browser.js:111 core:schema:warn Unknown property `recieve` for component/system `shadow`.
```
=> typo here receive

- [ ] https://192.168.1.15:8080/showcase/tracked-controls/
```
a-assets.js:44 Uncaught Error: <a-assets> must be a child of a <a-scene>.
    at AAssets.doConnectedCallback (a-assets.js:44:13)
    at AAssets.connectedCallback (a-assets.js:28:10)

https://192.168.1.15:8080/test/cylinders/
core:schema:warn Unknown property `radiusTop` for component/system `geometry`. 
browser.js:111 core:schema:warn Unknown property `radiusBottom` for component/system `geometry`.
```
- [ ] https://192.168.1.15:8080/test/raycaster/
```
core:schema:warn Unknown property `recursive` for component/system `raycaster`.
```

- [ ] https://192.168.1.15:8080/test/shaders/
```
core:schema:warn Default value `0 0 -1` does not match type `vec3` in component `undefined` 
```

- [ ] https://192.168.1.15:8080/test/visibility/
```
components:raycaster:warn [raycaster] For performance, please define raycaster.objects when using raycaster or cursor components to whitelist which entities to intersect with. e.g., raycaster="objects: [data-raycastable]". 
```

- [ ] https://192.168.1.15:8080/animation/arms/
```
core:schema:warn Unknown property `fill` for component/system `animation`.
```

- [ ] https://192.168.1.15:8080/animation/unfold/
```
core:schema:warn Unknown property `attribute` for component/system `animation`.
```

**Comment by dmarcos** [comment]
I'm addressing a few of these

**Comment by vincentfretin** [comment]
Great, please reference the issue in your commits and check the checkbox if you resolve a task here.
