### ISSUE TITLE
Potential issue when removing hand-controls in v1.4.0

### ISSUE THREAD

**Issue by wmurphyrd** [aframevr/aframe#5205]
**Description:**

Updating super-hands to 1.4.0, I started getting a new error in the unit tests. If a test uses the `hand-controls` component, then I get the following during teardown between tests:

```
LOG: '%ccore:a-entity:warn %cTried to remove `Object3D` of type:%c ', 'color: orange', 'color: inherit', 'color: orange', 'mesh', 'which was not defined.'

TypeError: Cannot read properties of undefined (reading 'charAt')
      at NewComponent.update (/tmp/node_modules/aframe/dist/aframe-master.js:14201:1 <- /tmp/8b0f0230f2e53b7234b5dd5f978537c4.browserify.js:34567:59)
      at NewComponent.initComponent (/tmp/node_modules/aframe/dist/aframe-master.js:26176:1 <- /tmp/8b0f0230f2e53b7234b5dd5f978537c4.browserify.js:46542:10)
      at NewComponent.updateProperties (/tmp/node_modules/aframe/dist/aframe-master.js:26145:1 <- /tmp/8b0f0230f2e53b7234b5dd5f978537c4.browserify.js:46511:12)
      at AEntity.updateComponent (/tmp/node_modules/aframe/dist/aframe-master.js:24983:1 <- /tmp/8b0f0230f2e53b7234b5dd5f978537c4.browserify.js:45349:17)
      at AEntity.updateComponents (/tmp/node_modules/aframe/dist/aframe-master.js:24960:1 <- /tmp/8b0f0230f2e53b7234b5dd5f978537c4.browserify.js:45326:12)
      at entityLoadCallback (/tmp/node_modules/aframe/dist/aframe-master.js:24751:1 <- /tmp/8b0f0230f2e53b7234b5dd5f978537c4.browserify.js:45117:12)
      at emitLoaded (/tmp/node_modules/aframe/dist/aframe-master.js:25685:1 <- /tmp/8b0f0230f2e53b7234b5dd5f978537c4.browserify.js:46051:9)
```

I changed out the controller component to `vive-controls` and the tests passed. 

- A-Frame Version: 1.4.0
- Platform / Device: headless chrome in unit tests 
- Reproducible Code Snippet or URL:  The test config & teardown I use is cribbed straight from A-Frame repo: https://github.com/c-frame/aframe-super-hands-component/blob/master/tests/__init.test.js

**Comment by dmarcos** [comment]
Sorry not familiar with your unit tests. Can you reproduce with https://glitch.com/~aframe ?

**Comment by vincentfretin** [comment]
I guess hand is undefined here in your test teardown
https://github.com/aframevr/aframe/blob/6c6f0da1fb6cc3be476fad94ab938e1d072aaa0d/src/components/hand-controls.js#L198
? but why?

**Comment by dmarcos** [comment]
Yeah we should determine if it's an actual A-Frame bug or a test bug

**Comment by vincentfretin** [comment]
It may be the same issue as #5203?
`hand-controls` is using `el.setAttribute('vive-controls', controlConfiguration);`  in the `update()` method.
Do you still have the issue with aframe master?

**Comment by wmurphyrd** [comment]
> I guess hand is undefined here in your test teardown
> 
> https://github.com/aframevr/aframe/blob/6c6f0da1fb6cc3be476fad94ab938e1d072aaa0d/src/components/hand-controls.js#L198
> 
> ? but why?

oh my god I'm sorry y'all - I had just not updated the tests for the previous breaking change with hand-controls going from single-prop to multi-prop.
