### ISSUE TITLE
[CLOSED] npm link from aframe-core repo checkout gives a fatal error.

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe#736]
<a href="https://github.com/nhirata"><img src="https://avatars.githubusercontent.com/u/1091409?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nhirata](https://github.com/nhirata)**
_Saturday Dec 12, 2015 at 03:37 GMT_
_Originally opened as https://github.com/aframevr/aframe-core/issues/655_

----

1. git clone https://github.com/aframevr/aframe-core
2. cd aframe-core
3. npm link

Expected: links
Actual: 
nhirata-19333:aframe-core nhirata$ npm link
npm ERR! git rev-list -n1 7391d13: fatal: ambiguous argument '7391d13': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 7391d13: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 7391d13: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 7391d13: 
npm ERR! git rev-list -n1 7391d13: fatal: ambiguous argument '7391d13': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 7391d13: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 7391d13: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 7391d13: 
npm ERR! git rev-list -n1 7391d13: fatal: ambiguous argument '7391d13': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 7391d13: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 7391d13: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 7391d13: 
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "link"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code 128

npm ERR! Command failed: git rev-list -n1 7391d13
npm ERR! fatal: ambiguous argument '7391d13': unknown revision or path not in the working tree.
npm ERR! Use '--' to separate paths from revisions, like this:
npm ERR! 'git <command> [<revision>...] -- [<file>...]'
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Projects/aframe-core/npm-debug.log

**Comment by ngokevin** [comment]
<a href="https://github.com/dmarcos"><img src="https://avatars.githubusercontent.com/u/39342?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dmarcos](https://github.com/dmarcos)**
_Sunday Dec 13, 2015 at 23:50 GMT_

----

Can you run the commands below and try agai?
git fetch origin
git checkout master
git reset --hard origin/master

**Comment by ngokevin** [comment]
<a href="https://github.com/dmarcos"><img src="https://avatars.githubusercontent.com/u/39342?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dmarcos](https://github.com/dmarcos)**
_Sunday Dec 13, 2015 at 23:50 GMT_

----

@cvan might have more insight on what it's going on

**Comment by ngokevin** [comment]
<a href="https://github.com/nhirata"><img src="https://avatars.githubusercontent.com/u/1091409?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nhirata](https://github.com/nhirata)**
_Monday Dec 14, 2015 at 10:28 GMT_

----

still getting the same error, looking at more /Projects/aframe-core/npm-debug.log :
...
872 verbose addLocalTarball adding from inside cache /Users/nhirata/.npm/webvr-polyfill/0.2.0/package.tgz
873 verbose addRemoteGit data._from: borismus/webvr-polyfill#3f47796
874 verbose addRemoteGit data._resolved: git://github.com/borismus/webvr-polyfill.git#3f477966abd594f37914c925d165c8fc8b2f05da
875 silly cache afterAdd webvr-polyfill@0.2.0
876 verbose afterAdd /Users/nhirata/.npm/webvr-polyfill/0.2.0/package/package.json not in flight; writing
877 verbose afterAdd /Users/nhirata/.npm/webvr-polyfill/0.2.0/package/package.json written
878 verbose updateRemote git fetch -a origin (git@github.com:cvan/budo.git)
879 verbose setPermissions cvan/budo#7391d13 set permissions on /Users/nhirata/.npm/_git-remotes/git-github-com-cvan-budo-git-0425493e
880 verbose resolveHead cvan/budo#7391d13 original treeish: 7391d13
881 info git [ 'rev-list', '-n1', '7391d13' ]
882 error git rev-list -n1 7391d13: fatal: ambiguous argument '7391d13': unknown revision or path not in the working tree.
882 error git rev-list -n1 7391d13: Use '--' to separate paths from revisions, like this:
882 error git rev-list -n1 7391d13: 'git <command> [<revision>...] -- [<file>...]'
883 verbose stack Error: Command failed: git rev-list -n1 7391d13
883 verbose stack fatal: ambiguous argument '7391d13': unknown revision or path not in the working tree.
883 verbose stack Use '--' to separate paths from revisions, like this:
883 verbose stack 'git <command> [<revision>...] -- [<file>...]'
883 verbose stack
883 verbose stack     at ChildProcess.exithandler (child_process.js:751:12)
883 verbose stack     at ChildProcess.emit (events.js:110:17)
883 verbose stack     at maybeClose (child_process.js:1015:16)
883 verbose stack     at Socket.<anonymous> (child_process.js:1183:11)
883 verbose stack     at Socket.emit (events.js:107:17)
883 verbose stack     at Pipe.close (net.js:485:12)
884 verbose cwd /Projects/aframe-core

**Comment by ngokevin** [comment]
<a href="https://github.com/cvan"><img src="https://avatars.githubusercontent.com/u/203725?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [cvan](https://github.com/cvan)**
_Monday Dec 14, 2015 at 17:18 GMT_

----

think this had something to do with rebase, not sure. but cvan/budo has been upgraded to mattdesl/budo. if you pull and install again, it should be working. let me know.

**Comment by ngokevin** [comment]
<a href="https://github.com/dmarcos"><img src="https://avatars.githubusercontent.com/u/39342?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dmarcos](https://github.com/dmarcos)**
_Monday Dec 14, 2015 at 18:00 GMT_

----

This is a real bug master still points to the cvan's budo repo:
https://github.com/aframevr/aframe-core/blob/master/package.json#L22

**Comment by ngokevin** [comment]
<a href="https://github.com/dmarcos"><img src="https://avatars.githubusercontent.com/u/39342?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dmarcos](https://github.com/dmarcos)**
_Monday Dec 14, 2015 at 18:02 GMT_

----

@nhirata I just merged dev into master so this problem should be gone. Please reopen it necessary
